---
- !ruby/struct:VCR::HTTPInteraction
  request: !ruby/struct:VCR::Request
    method: :get
    uri: https://app.viralheat.com:443/social/api/sentiment/train?api_key=<API_KEY>&text=I%20don't%20like%20coffee'&mood=negative
    body: 
    headers: 
  response: !ruby/struct:VCR::Response
    status: !ruby/struct:VCR::ResponseStatus
      code: 200
      message: OK
    headers:
      server:
      - nginx/1.4.4
      date:
      - Tue, 10 Jun 2014 21:57:28 GMT
      content-type:
      - application/json; charset=utf-8
      content-length:
      - '27'
      strict-transport-security:
      - max-age=31536000
      x-ua-compatible:
      - IE=Edge,chrome=1
      etag:
      - ! '"27295311aefc7e77f813327449386332"'
      cache-control:
      - max-age=0, private, must-revalidate
      x-request-id:
      - 088e0e0eb978690694185d4045533b01
      x-rack-cache:
      - miss
      status:
      - '200'
    body: ! '{"status":200,"error":null}'
    http_version: '1.1'
